name: Domotics 3D
slug: domotics_3d
version: "10.1.1"
description: Domotics 3D Control Panel

arch:
  - amd64
  - aarch64

startup: application
boot: auto

ingress: true
ingress_port: 1338
panel_icon: mdi:cube-outline
panel_title: Domotics 3D

host_network: false
init: false

options:
  remote_url: ""
  remote_token: ""
  local_url: ""
  local_token: ""

schema:
  remote_url: url?
  remote_token: password?
  local_url: url?
  local_token: password?

ports: {}
