name: Domotics 3D
slug: domotics_3d
version: "10.1.1"
description: Domotics 3D Control Panel

arch:
  - amd64
  - armv7
  - armhf
  - aarch64

startup: application
boot: auto

ingress: true
ingress_port: 1338
panel_icon: mdi:cube-outline
panel_title: Domotics 3D

host_network: false
init: false

options:
  remote_url: "wss://REMOTE URL/api/websocket"
  remote_token: "REMOTE TOKEN"
  local_url: "ws://[IP_ADDRESS]/api/websocket"
  local_token: "LOCAL TOKEN"

schema:
  remote_url:
    description: Remote Home Assistant websocket URL
    type: str
    default: "wss://REMOTE URL/api/websocket"
  remote_token:
    description: Remote Home Assistant access token
    type: str
    default: "REMOTE TOKEN"
  local_url:
    description: Local Home Assistant websocket URL
    type: str
    default: "ws://[IP_ADDRESS]/api/websocket"
  local_token:
    description: Local Home Assistant access token
    type: str
    default: "LOCAL TOKEN"

ports: {}
