name: Domotics 3D
slug: domotics_3d
version: "10.0.3"
description: Domotics 3D Control Panel

arch:
  - amd64
  - armv7
  - armhf
  - aarch64

startup: application
boot: auto

ingress: true
ingress_port: 1338
panel_icon: mdi:cube-outline
panel_title: Domotics 3D

host_network: false
init: false

options: {}
schema: {}

ports: {}
